'use client';
import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
// @ts-ignore Shared engine is tested independently with Node.
import {seed,act,draw,catalog,tickets,unresolved,duplicates,valid} from '@/lib/tombola.mjs';
const FORM_URL='https://docs.google.com/forms/d/e/1FAIpQLSfh7Zf-Doce8XpT0T9L6Ddkc6XzOOYAZ7JUii9Q-FJBGPYhTA/viewform?usp=publish-editor'; const FORM_EMBED_URL='https://docs.google.com/forms/d/e/1FAIpQLSfh7Zf-Doce8XpT0T9L6Ddkc6XzOOYAZ7JUii9Q-FJBGPYhTA/viewform?embedded=true'; const SHEET_API_URL='https://script.google.com/macros/s/AKfycbyH5PlTgpQWYj6spuvocTz-ZZ7KXKJBnrsPOnThwIyvP_vd_DbYlCrXCC5BDQAXRuoO/exec';
export default function Home(){
 const [s,setS]=useState<any>(seed),[message,setMessage]=useState('Conectando con la hoja de respuestas…'),[tab,setTab]=useState('review'),[reason,setReason]=useState(''),[business,setBusiness]=useState('B001'),[amount,setAmount]=useState(25000),[spinning,setSpinning]=useState(false),[liveRows,setLiveRows]=useState<any[]|null>(null);
 useEffect(()=>{if(!SHEET_API_URL)return; let active=true; let script:HTMLScriptElement|null=null; let callbackName=''; const cleanup=()=>{if(script)script.remove(); if(callbackName)delete (window as any)[callbackName]; script=null; callbackName=''}; const load=()=>{cleanup(); callbackName='__tombolaSheet_'+Math.random().toString(36).slice(2); (window as any)[callbackName]=(data:any)=>{if(active&&data?.rows)setLiveRows(data.rows.filter((r:any)=>r['Nombre de la persona compradora']||r['Identificador completo de factura']).map((r:any,i:number)=>({id:'sheet-'+(r.row||i),sheetRow:Number(r.row||0),name:r['Nombre de la persona compradora']||'Sin nombre',contact:r['Correo o contacto']||'',business:r['Identificador de negocio']||'',series:r['Serie / sucursal']||'',invoice:r['Identificador completo de factura']||'',date:r['Fecha de la factura']||'',amount:Number(String(r['Monto de la factura en colones']||r['Monto de compra en colones']||0).replace(/[^0-9.-]/g,''))||0,multiplier:Number(r['Multiplicador']||1),duplicateCount:Number(r['Coincidencias']||1),status:(Number(r['Coincidencias']||1)>1?(r['Estado revisión']||'Pendiente · coincidencia'):'Aprobada'),photo:'',count:Number(r['Tickets calculados']||0)}))); cleanup()}; script=document.createElement('script'); script.src=SHEET_API_URL+'?callback='+encodeURIComponent(callbackName); script.async=true; script.onerror=()=>{if(active)setMessage('La hoja aún no está disponible para la interfaz.'); cleanup()}; document.head.appendChild(script)}; load(); const timer=setInterval(load,15000); return()=>{active=false;clearInterval(timer);cleanup()}},[]);
 const reviewRows=liveRows?liveRows.filter((r:any)=>Number(r.duplicateCount||1)>1&&r.status!=='Aprobada'&&r.status!=='Rechazada'):[]; const displayedCount=liveRows?liveRows.length:0; const displayedPending=reviewRows.length; const displayedTickets=liveRows?liveRows.filter((r:any)=>r.status==='Aprobada').reduce((n:number,r:any)=>n+(Number(r.count)||0),0):0;
 const sheetAction=(row:number,status:string)=>{if(!row)return;const callback='__tombolaWrite_'+Math.random().toString(36).slice(2);const script=document.createElement('script');(window as any)[callback]=(data:any)=>{delete (window as any)[callback];script.remove();if(data?.result?.ok){setMessage(status==='Aprobada'?'Factura aprobada en la hoja.':'Factura rechazada en la hoja.');window.location.reload();}else setMessage('No se pudo actualizar la hoja.');};script.onerror=()=>{delete (window as any)[callback];script.remove();setMessage('No se pudo actualizar la hoja.')};script.src=SHEET_API_URL+'?action=review&row='+encodeURIComponent(row)+'&status='+encodeURIComponent(status)+'&reason='+encodeURIComponent(reason)+'&callback='+encodeURIComponent(callback);document.head.appendChild(script)};
 const perform=(action:string,p:any={})=>{try{setS(act(s,action,p));setMessage('Operación registrada.');}catch(e:any){setMessage(e.message);}};
 const exportData=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='tombola-padron-historial.json';a.click();URL.revokeObjectURL(url);};
 const liveTickets=liveRows?liveRows.filter((r:any)=>r.status==='Aprobada'&&(Number(r.count)||0)>0).reduce((out:any[],r:any)=>{const previous=out.length?out[out.length-1].end:0;const count=Number(r.count)||0;out.push({...r,start:previous+1,end:previous+count});return out},[]):null;
 const runLiveDraw=()=>{if(!liveTickets?.length)return;const totalTickets=liveTickets[liveTickets.length-1].end;const ticket=Math.floor(Math.random()*totalTickets)+1;const winner=liveTickets.find((l:any)=>ticket>=l.start&&ticket<=l.end)||liveTickets[0];setS({...s,result:{ticket,name:winner.name,contact:winner.contact,total:totalTickets,at:new Date().toLocaleString('es-CR')}});setSpinning(true);setTimeout(()=>setSpinning(false),1800);setMessage('Sorteo ejecutado con tickets aprobados.');};
 const total=s.ledger.filter((l:any)=>valid(s,l)).reduce((n:number,l:any)=>n+l.count,0);
 return <main><header><div className="brand">D<span>/</span>12</div><div><p className="eyebrow">CAMPAÑA COMERCIAL</p><h1>Tómbola de diciembre</h1></div><a className="form-link" href={FORM_URL} target="_blank" rel="noreferrer">Registrar una compra →</a><span className="sheet-status">{liveRows?'Hoja conectada':'Conectando hoja…'}</span></header><div className="notice">Para participar, use el formulario vinculado. Las respuestas llegan a la hoja privada del organizador. La carga de fotos exige iniciar sesión en Google.</div>
 <section className="overview"><div><p className="eyebrow">CADA COMPRA CUENTA</p><h2>De la factura<br/>a la participación.</h2><p>Por cada ₡10.000 completos: <strong>1 ticket</strong>, o <strong>2 en patrocinadores</strong>. Cada factura se calcula por separado; los sobrantes no se acumulan.</p><span className="status">{s.snapshot?'Padrón congelado':s.closed?'Recepción cerrada':'Recepción abierta'} · Diciembre 2026</span></div><div className="metrics"><article><b>{displayedCount}</b><span>facturas recibidas</span></article><article><b>{displayedPending}</b><span>por revisar</span></article><article className="ticket-metric"><b>{displayedTickets}</b><span>tickets válidos asignados</span></article></div></section>
 <Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="navigation"><TabsTrigger value="register">01 · Registrar</TabsTrigger><TabsTrigger value="review">02 · Revisar</TabsTrigger><TabsTrigger value="tickets">03 · Tickets</TabsTrigger><TabsTrigger value="draw">Extra · Sorteo</TabsTrigger><TabsTrigger value="guide">Guía</TabsTrigger></TabsList><p className="feedback" role="status">{message}</p>
 <TabsContent value="register"><section className="panel register-panel"><div className="section-heading"><div><h2>Registrar una compra</h2><p>Complete el formulario aquí mismo. Sus respuestas llegan directamente a la hoja privada del organizador.</p></div><a className="form-link" href={FORM_URL} target="_blank" rel="noreferrer">Abrir en otra pestaña ↗</a></div><div className="form-embed"><iframe title="Formulario de registro de compra" src={FORM_EMBED_URL} loading="lazy"/></div><p className="embed-note">La carga de la foto puede pedirle iniciar sesión en Google. Si el formulario no aparece, use “Abrir en otra pestaña”.</p></section></TabsContent>
 <TabsContent value="review"><section className="panel"><div className="section-heading"><div><h2>Revisión de coincidencias</h2><p>Solo aparecen facturas con coincidencias detectadas en la hoja.</p></div><Button onClick={()=>perform('assign')} disabled={!liveRows||!!s.snapshot}>Asignar lote aprobado</Button></div><label className="reason">Motivo para la siguiente revisión o anulación<Input value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="table-wrap"><Table><TableHeader><TableRow>{['Comprador / factura','Negocio / monto','Revisión','Acciones'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{reviewRows.map((r:any)=><TableRow key={r.id}><TableCell><strong>{r.name}</strong><small>{r.series} / {r.invoice} · {r.date}</small>{r.photo.startsWith('data:image/')?<details><summary>Ver foto</summary><img src={r.photo} alt="Comprobante de compra" width="220"/></details>:<small>{liveRows?'Comprobante recibido':'Comprobante pendiente'} · {r.amount.toLocaleString('es-CR')} CRC</small>}</TableCell><TableCell>{catalog.find((b:any)=>b.id===r.business)?.name}<small>₡{r.amount.toLocaleString('es-CR')} · ×{r.multiplier}</small></TableCell><TableCell><span className={'badge '+(unresolved(s,r)?'warning':'')}>{unresolved(s,r)?'Coincidencia por resolver':r.status}</span>{r.duplicateCount>1&&<small>{r.duplicateCount} envíos coincidentes</small>}</TableCell><TableCell><div className="actions"><Button variant="outline" size="sm" disabled={!liveRows||!!s.snapshot||unresolved(s,r)} onClick={()=>liveRows?sheetAction(r.sheetRow,'Aprobada'):perform('review',{id:r.id,status:'Aprobada',reason})}>Aprobar</Button><Button variant="outline" size="sm" disabled={!liveRows||!!s.snapshot} onClick={()=>liveRows?sheetAction(r.sheetRow,'Rechazada'):perform(s.ledger.some((l:any)=>l.id===r.id)?'void':'review',{id:r.id,status:'Rechazada',reason})}>Rechazar / anular</Button>{unresolved(s,r)&&<Button size="sm" variant="outline" disabled={!!liveRows} onClick={()=>perform('resolve',{id:r.id,reason})}>Conservar este envío</Button>}</div></TableCell></TableRow>)}</TableBody></Table></div></section></TabsContent>
 <TabsContent value="tickets"><section className="panel"><div className="section-heading"><div><h2>Tickets con números estables</h2><p>Repita el lote sin duplicar tickets. Anular una factura no reutiliza sus números.</p></div><Button onClick={()=>perform('assign')} disabled={!!s.snapshot}>Asignar lote</Button></div>{liveRows?(liveTickets?.length?liveTickets.map((l:any)=><article className="ticket" key={l.id}><div><strong>{l.name}</strong><small>Válido · {l.count} participaciones</small></div><b>{String(l.start).padStart(6,'0')} — {String(l.end).padStart(6,'0')}</b><span>₡{l.amount.toLocaleString('es-CR')} × {l.multiplier}</span></article>):<p className="empty">Apruebe las facturas en Revisar para generar tickets.</p>):(!s.ledger.length?<p className="empty">Apruebe las facturas en Revisión y asigne el lote.</p>:s.ledger.map((l:any)=><article className="ticket" key={l.id}><div><strong>{l.name}</strong><small>{valid(s,l)?'Válido':'Excluido / retenido'} · {l.count} participaciones</small></div><b>{String(l.start).padStart(6,'0')} — {String(l.end).padStart(6,'0')}</b><span>₡{l.amount.toLocaleString('es-CR')} × {l.multiplier}</span></article>))}<Button variant="outline" onClick={exportData}>Exportar padrón e historial</Button></section></TabsContent>
 <TabsContent value="draw"><section className="draw-grid"><div className="panel"><p className="eyebrow">EXTRA OPCIONAL · ALCANCE SEPARADO</p><h2>Un ticket, una oportunidad.</h2><p>Cierre recepción, termine revisión y asigne el lote. Después cree una copia fija de los tickets válidos.</p><div className="steps"><Button variant="outline" disabled={s.closed} onClick={()=>perform('close')}>1. Cerrar recepción</Button><Button variant="outline" disabled={!s.closed||!!s.snapshot} onClick={()=>perform('freeze')}>2. Congelar padrón</Button><Button disabled={liveRows?!liveTickets?.length||spinning:!s.snapshot||!!s.result||spinning} onClick={()=>{if(liveRows){runLiveDraw();}else{try{setS(draw(s));setSpinning(true);setTimeout(()=>setSpinning(false),1800);setMessage('Resultado registrado.');}catch(e:any){setMessage(e.message)}}}}>3. Sortear ticket</Button></div><p className="fine">Se elige entre números válidos, no entre facturas. Un resultado por padrón. No es un sorteo oficial ni una certificación legal.</p></div><div className={'draw-result '+(spinning?'spinning':'')}><p>{spinning?'Revelando el ticket seleccionado…':s.result?'RESULTADO DEL SORTEO':'TICKET GANADOR'}</p><strong>{s.result&&!spinning?String(s.result.ticket).padStart(6,'0'):'••••••'}</strong><h3>{s.result&&!spinning?s.result.name:'Listo cuando usted lo esté'}</h3><span>{s.result&&!spinning?s.result.contact:`${s.snapshot?.total??total} tickets en el padrón`}</span>{s.result&&!spinning&&<small>{s.result.at}<br/>Probabilidad individual 1/{s.result.total}</small>}</div></section></TabsContent>
 <TabsContent value="guide"><section className="panel guide"><h2>Cómo revisar el flujo</h2><ol><li>Registre las compras mediante el formulario vinculado.</li><li>Revise cada comprobante y marque la decisión correspondiente.</li><li>Asigne el lote aprobado para generar los tickets.</li><li>Cierre la recepción, congele el padrón y ejecute el sorteo.</li><li>Exporte el historial cuando necesite conservar un respaldo.</li></ol><h3>Base propuesta: Google Forms + Sheets</h3><p>El formulario real está vinculado a la hoja privada de respuestas del organizador. La carga nativa de fotos en Forms exige iniciar sesión en Google. Las coincidencias se detectan después del envío.</p><p>Solo el organizador define patrocinadores. Se conservan ceros iniciales. Un comprador puede registrar varias facturas.</p></section></TabsContent>
 </Tabs><details className="history"><summary>Historial de esta sesión ({s.history.length})</summary>{s.history.map((h:any,i:number)=><p key={i}>{h.at} · {h.actor} · {h.action}<small>{JSON.stringify(h.detail)}</small></p>)}</details><footer>D/12 · Herramienta de revisión · Las compras reales llegan por el formulario vinculado</footer></main>;
}




