'use client';
import {useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
// @ts-ignore Shared engine is tested independently with Node.
import {seed,act,draw,catalog,tickets,unresolved,duplicates,valid} from '@/lib/tombola.mjs';
export default function Home(){
 const [s,setS]=useState<any>(seed),[message,setMessage]=useState('Pruebe el flujo con cuatro compras ficticias precargadas.'),[tab,setTab]=useState('review'),[reason,setReason]=useState('Comprobante ficticio contrastado en la demo'),[business,setBusiness]=useState('B001'),[amount,setAmount]=useState(25000),[spinning,setSpinning]=useState(false);
 const perform=(action:string,p:any={})=>{try{setS(act(s,action,p));setMessage('Operación registrada.');}catch(e:any){setMessage(e.message);}};
 const exportData=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='tombola-DEMO-padron-historial.json';a.click();URL.revokeObjectURL(url);};
 const total=s.ledger.filter((l:any)=>valid(s,l)).reduce((n:number,l:any)=>n+l.count,0);
 return <main><header><div className="brand">D<span>/</span>12</div><div><p className="eyebrow">CAMPAÑA COMERCIAL</p><h1>Tómbola de diciembre</h1></div><span className="demo-label">DEMO · datos ficticios</span></header><div className="notice">Simulación en esta pestaña. No envía datos a Google ni guarda compras reales. Al recargar comienza de nuevo.</div>
 <section className="overview"><div><p className="eyebrow">CADA COMPRA CUENTA</p><h2>De la factura<br/>a la participación.</h2><p>Por cada ₡10.000 completos: <strong>1 ticket</strong>, o <strong>2 en patrocinadores</strong>. Cada factura se calcula por separado; los sobrantes no se acumulan.</p><span className="status">{s.snapshot?'Padrón congelado':s.closed?'Recepción cerrada':'Recepción abierta'} · Diciembre 2026, supuesto demo</span></div><div className="metrics"><article><b>{s.rows.length}</b><span>facturas recibidas</span></article><article><b>{s.rows.filter((r:any)=>r.status==='Pendiente'||unresolved(s,r)).length}</b><span>por revisar</span></article><article className="ticket-metric"><b>{total}</b><span>tickets válidos asignados</span></article></div></section>
 <Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="navigation"><TabsTrigger value="register">01 · Registrar</TabsTrigger><TabsTrigger value="review">02 · Revisar</TabsTrigger><TabsTrigger value="tickets">03 · Tickets</TabsTrigger><TabsTrigger value="draw">Extra · Sorteo</TabsTrigger><TabsTrigger value="guide">Guía</TabsTrigger></TabsList><p className="feedback" role="status">{message}</p>
 <TabsContent value="register"><section className="panel"><h2>Registrar una compra de prueba</h2><p>Use datos inventados. La foto permanece en memoria y no se sube a ningún servicio.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),file=f.get('photo') as File;if(!file?.size||file.size>5242880||!file.type.startsWith('image/')){setMessage('Seleccione una imagen ficticia de hasta 5 MB');return;}const photo=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)});perform('add',{name:f.get('name'),contact:f.get('contact'),business,series:f.get('series'),invoice:f.get('invoice'),date:f.get('date'),amount,photo});}}><div className="form-grid"><label>Nombre ficticio<Input name="name" defaultValue="Daniela Demo" required/></label><label>Correo ficticio<Input name="contact" type="email" defaultValue="demo@example.invalid" required/></label><label>Negocio<Select value={business} onValueChange={v=>setBusiness(String(v))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{catalog.map((b:any)=><SelectItem key={b.id} value={b.id}>{b.name} · ×{b.multiplier}</SelectItem>)}</SelectContent></Select></label><label>Serie / sucursal<Input name="series" defaultValue="S01" required/></label><label>Identificador completo de factura<Input name="invoice" defaultValue="000105" required/></label><label>Fecha<Input name="date" type="date" min="2026-12-01" max="2026-12-31" defaultValue="2026-12-12" required/></label><label>Monto en colones, sin decimales<Input type="number" min="0" step="1" value={amount} onChange={e=>setAmount(Number(e.target.value))} required/></label><label>Foto ficticia, máximo 5 MB<Input name="photo" type="file" accept="image/*" required/></label></div><div className="form-footer"><strong>{Number.isSafeInteger(amount)&&amount>=0?tickets(amount,catalog.find((b:any)=>b.id===business).multiplier):0} tickets estimados · sujetos a aprobación</strong><Button disabled={s.closed}>Registrar prueba</Button></div></form></section></TabsContent>
 <TabsContent value="review"><section className="panel"><div className="section-heading"><div><h2>Revisión del organizador</h2><p>Contraste la foto y documente la decisión antes de emitir tickets.</p></div><Button onClick={()=>perform('assign')} disabled={!!s.snapshot}>Asignar lote aprobado</Button></div><label className="reason">Motivo para la siguiente revisión o anulación<Input value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="table-wrap"><Table><TableHeader><TableRow>{['Comprador / factura','Negocio / monto','Revisión','Acciones'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{s.rows.map((r:any)=><TableRow key={r.id}><TableCell><strong>{r.name}</strong><small>{r.series} / {r.invoice} · {r.date}</small>{r.photo.startsWith('data:image/')?<details><summary>Ver foto</summary><img src={r.photo} alt="Comprobante de prueba" width="220"/></details>:<small>Comprobante ficticio · {r.amount.toLocaleString('es-CR')} CRC</small>}</TableCell><TableCell>{catalog.find((b:any)=>b.id===r.business)?.name}<small>₡{r.amount.toLocaleString('es-CR')} · ×{r.multiplier}</small></TableCell><TableCell><span className={'badge '+(unresolved(s,r)?'warning':'')}>{unresolved(s,r)?'Coincidencia por resolver':r.status}</span>{duplicates(s,r).length>1&&<small>{duplicates(s,r).length} envíos coincidentes</small>}</TableCell><TableCell><div className="actions"><Button variant="outline" size="sm" disabled={!!s.snapshot||unresolved(s,r)} onClick={()=>perform('review',{id:r.id,status:'Aprobada',reason})}>Aprobar</Button><Button variant="outline" size="sm" disabled={!!s.snapshot} onClick={()=>perform(s.ledger.some((l:any)=>l.id===r.id)?'void':'review',{id:r.id,status:'Rechazada',reason})}>Rechazar / anular</Button>{unresolved(s,r)&&<Button size="sm" variant="outline" onClick={()=>perform('resolve',{id:r.id,reason})}>Conservar este envío</Button>}<Button size="sm" variant="ghost" disabled={s.closed} onClick={()=>perform('duplicate',{id:r.id})}>Probar duplicado</Button></div></TableCell></TableRow>)}</TableBody></Table></div></section></TabsContent>
 <TabsContent value="tickets"><section className="panel"><div className="section-heading"><div><h2>Tickets con números estables</h2><p>Repita el lote sin duplicar tickets. Anular una factura no reutiliza sus números.</p></div><Button onClick={()=>perform('assign')} disabled={!!s.snapshot}>Asignar lote</Button></div>{!s.ledger.length?<p className="empty">Apruebe las facturas en Revisión y asigne el lote.</p>:s.ledger.map((l:any)=><article className="ticket" key={l.id}><div><strong>{l.name}</strong><small>{valid(s,l)?'Válido':'Excluido / retenido'} · {l.count} participaciones</small></div><b>{String(l.start).padStart(6,'0')} — {String(l.end).padStart(6,'0')}</b><span>₡{l.amount.toLocaleString('es-CR')} × {l.multiplier}</span></article>)}<Button variant="outline" onClick={exportData}>Exportar padrón e historial</Button></section></TabsContent>
 <TabsContent value="draw"><section className="draw-grid"><div className="panel"><p className="eyebrow">EXTRA OPCIONAL · ALCANCE SEPARADO</p><h2>Un ticket, una oportunidad.</h2><p>Cierre recepción, termine revisión y asigne el lote. Después cree una copia fija de los tickets válidos.</p><div className="steps"><Button variant="outline" disabled={s.closed} onClick={()=>perform('close')}>1. Cerrar recepción</Button><Button variant="outline" disabled={!s.closed||!!s.snapshot} onClick={()=>perform('freeze')}>2. Congelar padrón</Button><Button disabled={!s.snapshot||!!s.result||spinning} onClick={()=>{try{setS(draw(s));setSpinning(true);setTimeout(()=>setSpinning(false),1800);setMessage('Resultado de demostración registrado.');}catch(e:any){setMessage(e.message)}}}>3. Sortear ticket de prueba</Button></div><p className="fine">Se elige entre números válidos, no entre facturas. Un resultado por padrón. No es un sorteo oficial ni una certificación legal.</p></div><div className={'draw-result '+(spinning?'spinning':'')}><p>{spinning?'Revelando el ticket seleccionado…':s.result?'RESULTADO DE PRUEBA':'TICKET GANADOR'}</p><strong>{s.result&&!spinning?String(s.result.ticket).padStart(6,'0'):'••••••'}</strong><h3>{s.result&&!spinning?s.result.name:'Listo cuando usted lo esté'}</h3><span>{s.result&&!spinning?s.result.contact:`${s.snapshot?.total??total} tickets en el padrón`}</span>{s.result&&!spinning&&<small>{s.result.at}<br/>Probabilidad individual 1/{s.result.total}</small>}</div></section></TabsContent>
 <TabsContent value="guide"><section className="panel guide"><h2>Cómo probarlo</h2><ol><li>Apruebe las cuatro compras. Ana participa con dos facturas distintas.</li><li>Asigne el lote: 11 tickets. Repita el lote: siguen siendo 11.</li><li>Pruebe un duplicado: ambos envíos se retienen. Conserve el envío nuevo, apruébelo y asigne otra vez. El rango anterior queda anulado.</li><li>En el extra, cierre recepción, termine revisión, congele y sortee.</li><li>Exporte el historial antes de recargar o reiniciar.</li></ol><h3>Base propuesta: Google Forms + Sheets</h3><p>El formulario y la hoja reales son independientes de esta simulación. La carga nativa de fotos en Forms exige iniciar sesión en Google. Las coincidencias se detectan después del envío.</p><p>Solo el organizador define patrocinadores. Se conservan ceros iniciales. Un comprador puede registrar varias facturas.</p><h3>Costos sujetos a validación</h3><p>Base provisional: 15–22 horas, condicionada a la integración. Ejemplo interno: costo ₡240.000, venta ₡350.000, ganancia antes de impuestos ₡110.000, margen 31,4%. El sorteo opcional se cotiza aparte.</p><Button variant="outline" onClick={()=>{setS(seed());setSpinning(false);setMessage('Nueva simulación con cuatro compras ficticias.');}}>Reiniciar únicamente la demo</Button></section></TabsContent>
 </Tabs><details className="history"><summary>Historial de esta simulación ({s.history.length})</summary>{s.history.map((h:any,i:number)=><p key={i}>{h.at} · {h.actor} · {h.action}<small>{JSON.stringify(h.detail)}</small></p>)}</details><footer>D/12 · Demostración · Sin datos de una campaña real</footer></main>;
}
